services:
  - type: web
    name: afaris-real-estate-api
    env: node
    rootDir: server
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma db push
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.vercel.app
      - key: PORT
        value: 10000


