services:
  - type: web
    name: afaris-real-estate-api
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma db push
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: afaris-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.vercel.app
      - key: PORT
        value: 10000

databases:
  - name: afaris-db
    plan: free
    databaseName: afaris_real_estate

